import type { Movie, TimelineFlag } from "@/types/movie";

/**
 * SPOILER RULE
 * ────────────
 * Information that belongs to movie N may only ever be rendered once movie N is watched.
 * Concretely: `knowledge` is only written for movies the user has already finished, and the
 * UI reads it only for watched movies. Never add forward-looking notes to a movie's entry —
 * a viewer who is up to Iron Man 2 must be able to read the whole dashboard safely.
 *
 * Adding a movie later:
 *  1. append the entry (or fill in `knowledge` on an existing one)
 *  2. add any newly unlocked threads to `data/connections.ts`
 * Nothing else needs to change.
 */

/** Chronological viewing order. Movies only — series/specials are intentionally out of scope. */
export const MOVIES: Movie[] = [
  {
    id: "captain-america-the-first-avenger",
    title: "Captain America: The First Avenger",
    timelineOrder: 1,
    phase: 1,
    saga: "infinity",
    releaseYear: 2011,
    timelineLabel: "1943–1945",
    knowledge: {
      summary:
        "מלחמת העולם השנייה. Steve Rogers, מתגייס שנדחה שוב ושוב, נבחר לניסוי סופר-סולג'ר אמריקאי ויוצא למלחמה מול HYDRA — זרוע מדעית שפרשה מהנאצים ומחזיקה במקור אנרגיה עתיק שאינו מהעולם הזה.",
      concepts: [
        "ניסוי הסופר-סולג'ר הצליח פעם אחת בלבד ולא ניתן לשחזור",
        "HYDRA צומחת מתוך מנגנון צבאי קיים ולא מבחוץ",
        "קיימים בעולם מקורות אנרגיה שאינם אנושיים",
        "טכנולוגיה צבאית מתקדמת קשורה למשפחת Stark כבר בשנות ה-40",
        "Steve נעלם בקרח בסוף המלחמה ומתעורר עשרות שנים אחר כך בעידן המודרני",
      ],
      characters: [
        "Steve Rogers / Captain America",
        "Peggy Carter",
        "Bucky Barnes",
        "Howard Stark",
        "Red Skull",
        "Dr. Abraham Erskine",
      ],
      organizations: ["HYDRA", "SSR", "צבא ארצות הברית"],
      objects: ["Tesseract", "סרום הסופר-סולג'ר", "מגן הוויברניום"],
      connections: [],
    },
    review: {
      rottenTomatoesScore: 80,
      metacriticScore: 66,
      consensus:
        "הרפתקה מיושנת ברוחה עם אפקטים דיגיטליים מודרניים — אחד הפרקים הבטוחים והאמינים ביותר ביקום הקולנועי של מארוול.",
      source: "Rotten Tomatoes",
      sourceUrl: "https://www.rottentomatoes.com/m/captain_america_the_first_avenger",
    },
  },
  {
    id: "captain-marvel",
    title: "Captain Marvel",
    timelineOrder: 2,
    phase: 3,
    saga: "infinity",
    releaseYear: 2019,
    timelineLabel: "1995",
    knowledge: {
      summary:
        "1995. לוחמת בשם Vers מגלה שהזיכרונות שלה הושתלו ושהמלחמה שבה נלחמה אינה מה שסיפרו לה. במקביל, סוכן צעיר ב-S.H.I.E.L.D בשם Nick Fury נתקל לראשונה בחיים מחוץ לכדור הארץ.",
      concepts: [
        "ה-MCU רחב בהרבה מכדור הארץ",
        "קיימים גזעים חייזריים — Kree ו-Skrulls — עם סכסוך ארוך ביניהם",
        "Carol Danvers מקבלת את כוחה מאנרגיה שמקורה ב-Tesseract",
        "Fury מבין שהאנושות אינה לבד ושהיא אינה ערוכה לכך",
        "מכאן נולד הרעיון של Avengers Initiative",
      ],
      characters: [
        "Carol Danvers / Captain Marvel",
        "Nick Fury",
        "Phil Coulson",
        "Maria Rambeau",
        "Talos",
        "Yon-Rogg",
      ],
      organizations: ["S.H.I.E.L.D", "Kree Starforce", "Skrulls"],
      objects: ["Tesseract", "מכשיר קשר לחירום שנשאר בידי Fury"],
      connections: [
        "ה-Tesseract שראית במלחמת העולם השנייה חוזר — הפעם רחוק מכדור הארץ",
        "S.H.I.E.L.D הוא ההמשך המוסדי של גופי הביטחון והמחקר שפעלו כבר בשנות ה-40",
      ],
    },
    review: {
      rottenTomatoesScore: 79,
      metacriticScore: 64,
      consensus:
        "עמוס באקשן, הומור ורגעים ויזואליים — Captain Marvel מציג את הגיבורה החדשה של ה-MCU עם סיפור מקור שמנצל היטב את הנוסחה המוכרת של הפרנצ'ייז.",
      source: "Rotten Tomatoes",
      sourceUrl: "https://www.rottentomatoes.com/m/captain_marvel",
    },
  },
  {
    id: "iron-man",
    title: "Iron Man",
    timelineOrder: 3,
    phase: 1,
    saga: "infinity",
    releaseYear: 2008,
    timelineLabel: "2010",
    knowledge: {
      summary:
        "Tony Stark, יורש תעשיית נשק ומהנדס יוצא דופן, נחטף ובונה בשבי כור אנרגיה זעיר וחליפת שריון כדי לברוח. בחזרתו הוא עוצר את ייצור הנשק ומגלה שהאיום האמיתי יושב בתוך החברה שלו.",
      concepts: [
        "Arc Reactor הוא מקור אנרגיה נייד ורב-עוצמה",
        "חליפת Iron Man היא הנדסה אנושית, לא כוח על",
        "Tony חושף בפומבי שהוא Iron Man ומוותר על זהות כפולה",
        "S.H.I.E.L.D מתחיל להתעניין באנשים יוצאי דופן ולא רק באיומים",
      ],
      characters: [
        "Tony Stark / Iron Man",
        "Pepper Potts",
        "James Rhodes",
        "Obadiah Stane",
        "Ho Yinsen",
        "Nick Fury",
      ],
      organizations: ["Stark Industries", "S.H.I.E.L.D", "Ten Rings"],
      objects: ["Arc Reactor", "שריון Mark I", "שריון Mark III"],
      connections: [
        "Nick Fury, שאותו פגשת ב-1995, פונה עכשיו ל-Tony ומזכיר את Avengers Initiative",
        "Howard Stark מ-The First Avenger הוא האב שהשאיר ל-Tony את החברה ואת הטכנולוגיה",
      ],
    },
    review: {
      rottenTomatoesScore: 94,
      metacriticScore: 79,
      consensus:
        "מונע על ידי הקסם התוסס של Robert Downey Jr., Iron Man מזריק טורבו לז'אנר גיבורי-העל עם חוכמה עדינה ותחושת כיף מדבקת.",
      source: "Rotten Tomatoes",
      sourceUrl: "https://www.rottentomatoes.com/m/iron_man",
    },
  },
  {
    id: "iron-man-2",
    title: "Iron Man 2",
    timelineOrder: 4,
    phase: 1,
    saga: "infinity",
    releaseYear: 2010,
    timelineLabel: "2011",
    knowledge: {
      summary:
        "הפלדיום שמניע את הכור בחזה של Tony מרעיל אותו לאט, בזמן שהממשל דורש שיעביר את הטכנולוגיה לידיים אחרות. במקביל מגיע Ivan Vanko, בנו של שותף ותיק של Howard Stark, לגבות חוב מהדור הקודם.",
      concepts: [
        "הדבר שמחזיק את Tony בחיים הוא גם הדבר שהורג אותו",
        "סכסוך מהדור של Howard ממשיך לדור של Tony",
        "Justin Hammer מייצג את התחרות המסחרית-צבאית מול Stark",
        "Natasha Romanoff מתגלה כסוכנת S.H.I.E.L.D שהושתלה בחברה",
        "S.H.I.E.L.D לא רק מתבונן — הוא מעריך את Tony ומחליט מה לעשות איתו",
      ],
      characters: [
        "Tony Stark",
        "Ivan Vanko / Whiplash",
        "Justin Hammer",
        "Natasha Romanoff / Black Widow",
        "James Rhodes / War Machine",
        "Nick Fury",
        "Pepper Potts",
      ],
      organizations: ["S.H.I.E.L.D", "Stark Industries", "Hammer Industries"],
      objects: [
        "יסוד חדש שנגזר ממחקר ישן של Howard Stark",
        "שריון War Machine",
        "Arc Reactor",
      ],
      connections: [
        "המחקר של Howard Stark הוא זה שמציל בסוף את חייו של Tony",
        "S.H.I.E.L.D, שהיה ברקע ב-Iron Man, הופך לגורם פעיל שמנטר ומעריך",
        "העימות מול Vanko הוא המשך ישיר של שותפות שנכשלה בדור של Howard",
      ],
    },
    review: {
      rottenTomatoesScore: 72,
      metacriticScore: 57,
      consensus:
        "לא בדיוק אותה נשימת אוויר צח כמו Iron Man הראשון, אבל ההמשך מתקרב אליה עם ביצועים טובים ועלילה עמוסת אקשן.",
      source: "Rotten Tomatoes",
      sourceUrl: "https://www.rottentomatoes.com/m/iron_man_2",
    },
  },

  /* ── מכאן והלאה: מטא-דאטה בטוחה בלבד. אין תקצירים, אין דמויות, אין ספוילרים. ── */

  {
    id: "the-incredible-hulk",
    title: "The Incredible Hulk",
    timelineOrder: 5,
    phase: 1,
    saga: "infinity",
    releaseYear: 2008,
    timelineLabel: "2011",
  },
  {
    id: "thor",
    title: "Thor",
    timelineOrder: 6,
    phase: 1,
    saga: "infinity",
    releaseYear: 2011,
    timelineLabel: "2011",
  },
  {
    id: "the-avengers",
    title: "The Avengers",
    timelineOrder: 7,
    phase: 1,
    saga: "infinity",
    releaseYear: 2012,
    timelineLabel: "2012",
  },
  {
    id: "thor-the-dark-world",
    title: "Thor: The Dark World",
    timelineOrder: 8,
    phase: 2,
    saga: "infinity",
    releaseYear: 2013,
    timelineLabel: "2013",
  },
  {
    id: "iron-man-3",
    title: "Iron Man 3",
    timelineOrder: 9,
    phase: 2,
    saga: "infinity",
    releaseYear: 2013,
    timelineLabel: "2012–2013",
  },
  {
    id: "captain-america-the-winter-soldier",
    title: "Captain America: The Winter Soldier",
    timelineOrder: 10,
    phase: 2,
    saga: "infinity",
    releaseYear: 2014,
    timelineLabel: "2014",
  },
  {
    id: "guardians-of-the-galaxy",
    title: "Guardians of the Galaxy",
    timelineOrder: 11,
    phase: 2,
    saga: "infinity",
    releaseYear: 2014,
    timelineLabel: "2014",
  },
  {
    id: "guardians-of-the-galaxy-vol-2",
    title: "Guardians of the Galaxy Vol. 2",
    timelineOrder: 12,
    phase: 3,
    saga: "infinity",
    releaseYear: 2017,
    timelineLabel: "2014",
  },
  {
    id: "avengers-age-of-ultron",
    title: "Avengers: Age of Ultron",
    timelineOrder: 13,
    phase: 2,
    saga: "infinity",
    releaseYear: 2015,
    timelineLabel: "2015",
  },
  {
    id: "ant-man",
    title: "Ant-Man",
    timelineOrder: 14,
    phase: 2,
    saga: "infinity",
    releaseYear: 2015,
    timelineLabel: "2015",
  },
  {
    id: "captain-america-civil-war",
    title: "Captain America: Civil War",
    timelineOrder: 15,
    phase: 3,
    saga: "infinity",
    releaseYear: 2016,
    timelineLabel: "2016",
  },
  {
    id: "black-widow",
    title: "Black Widow",
    timelineOrder: 16,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2021,
    timelineLabel: "2016",
  },
  {
    id: "black-panther",
    title: "Black Panther",
    timelineOrder: 17,
    phase: 3,
    saga: "infinity",
    releaseYear: 2018,
    timelineLabel: "2016",
  },
  {
    id: "spider-man-homecoming",
    title: "Spider-Man: Homecoming",
    timelineOrder: 18,
    phase: 3,
    saga: "infinity",
    releaseYear: 2017,
    timelineLabel: "2016",
  },
  {
    id: "doctor-strange",
    title: "Doctor Strange",
    timelineOrder: 19,
    phase: 3,
    saga: "infinity",
    releaseYear: 2016,
    timelineLabel: "2016–2017",
  },
  {
    id: "thor-ragnarok",
    title: "Thor: Ragnarok",
    timelineOrder: 20,
    phase: 3,
    saga: "infinity",
    releaseYear: 2017,
    timelineLabel: "2017",
  },
  {
    id: "ant-man-and-the-wasp",
    title: "Ant-Man and the Wasp",
    timelineOrder: 21,
    phase: 3,
    saga: "infinity",
    releaseYear: 2018,
    timelineLabel: "2018",
  },
  {
    id: "avengers-infinity-war",
    title: "Avengers: Infinity War",
    timelineOrder: 22,
    phase: 3,
    saga: "infinity",
    releaseYear: 2018,
    timelineLabel: "2018",
  },
  {
    id: "avengers-endgame",
    title: "Avengers: Endgame",
    timelineOrder: 23,
    phase: 3,
    saga: "infinity",
    releaseYear: 2019,
    timelineLabel: "2018 · 2023",
    milestone: true,
  },
  {
    id: "shang-chi-and-the-legend-of-the-ten-rings",
    title: "Shang-Chi and the Legend of the Ten Rings",
    timelineOrder: 24,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2021,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "spider-man-far-from-home",
    title: "Spider-Man: Far From Home",
    timelineOrder: 25,
    phase: 3,
    saga: "infinity",
    releaseYear: 2019,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "eternals",
    title: "Eternals",
    timelineOrder: 26,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2021,
    timelineLabel: "אחרי Endgame · רקע עתיק",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "spider-man-no-way-home",
    title: "Spider-Man: No Way Home",
    timelineOrder: 27,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2021,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame", "multiverse"],
  },
  {
    id: "doctor-strange-in-the-multiverse-of-madness",
    title: "Doctor Strange in the Multiverse of Madness",
    timelineOrder: 28,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2022,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame", "multiverse"],
  },
  {
    id: "black-panther-wakanda-forever",
    title: "Black Panther: Wakanda Forever",
    timelineOrder: 29,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2022,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "thor-love-and-thunder",
    title: "Thor: Love and Thunder",
    timelineOrder: 30,
    phase: 4,
    saga: "multiverse",
    releaseYear: 2022,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "ant-man-and-the-wasp-quantumania",
    title: "Ant-Man and the Wasp: Quantumania",
    timelineOrder: 31,
    phase: 5,
    saga: "multiverse",
    releaseYear: 2023,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame", "multiverse"],
  },
  {
    id: "guardians-of-the-galaxy-vol-3",
    title: "Guardians of the Galaxy Vol. 3",
    timelineOrder: 32,
    phase: 5,
    saga: "multiverse",
    releaseYear: 2023,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "the-marvels",
    title: "The Marvels",
    timelineOrder: 33,
    phase: 5,
    saga: "multiverse",
    releaseYear: 2023,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "deadpool-and-wolverine",
    title: "Deadpool & Wolverine",
    timelineOrder: 34,
    phase: 5,
    saga: "multiverse",
    releaseYear: 2024,
    timelineLabel: "לא לינארי",
    timelineFlags: ["post-endgame", "tva", "multiverse"],
  },
  {
    id: "captain-america-brave-new-world",
    title: "Captain America: Brave New World",
    timelineOrder: 35,
    phase: 5,
    saga: "multiverse",
    releaseYear: 2025,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "thunderbolts",
    title: "Thunderbolts*",
    timelineOrder: 36,
    phase: 5,
    saga: "multiverse",
    releaseYear: 2025,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
  {
    id: "the-fantastic-four-first-steps",
    title: "The Fantastic Four: First Steps",
    timelineOrder: 37,
    phase: 6,
    saga: "multiverse",
    releaseYear: 2025,
    timelineLabel: "יקום חלופי",
    timelineFlags: ["alternate-universe"],
  },
  {
    id: "spider-man-brand-new-day",
    title: "Spider-Man: Brand New Day",
    timelineOrder: 38,
    phase: 6,
    saga: "multiverse",
    releaseYear: 2026,
    timelineLabel: "אחרי Endgame",
    timelineFlags: ["post-endgame"],
  },
];

/** Sorted once, at module level, so views never re-sort. */
export const MOVIES_IN_TIMELINE_ORDER: readonly Movie[] = [...MOVIES].sort(
  (a, b) => a.timelineOrder - b.timelineOrder,
);

export const MOVIE_IDS: ReadonlySet<string> = new Set(MOVIES.map((m) => m.id));

/** The real, known progress. Reset returns here — never to zero. */
export const DEFAULT_WATCHED_IDS: readonly string[] = [
  "captain-america-the-first-avenger",
  "captain-marvel",
  "iron-man",
  "iron-man-2",
];

export const ENDGAME_ID = "avengers-endgame";

export const TIMELINE_FLAG_LABELS: Record<TimelineFlag, string> = {
  "post-endgame": "אחרי Endgame",
  multiverse: "מולטיוורס",
  tva: "TVA",
  "alternate-universe": "יקום חלופי",
};

export function getMovieById(id: string): Movie | undefined {
  return MOVIES.find((movie) => movie.id === id);
}
